# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 5) do

  create_table "addresses", :force => true do |t|
    t.integer "user_id",                         :null => false
    t.string  "name"
    t.string  "line_1",          :default => "", :null => false
    t.string  "line_2"
    t.string  "city",            :default => "", :null => false
    t.integer "state_id",                        :null => false
    t.string  "province_region"
    t.string  "zip_postal_code"
    t.integer "country_id",                      :null => false
  end

  create_table "sellers", :force => true do |t|
    t.integer  "user_id",                         :null => false
    t.string   "company_name"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.float    "capitalization", :default => 0.0
  end

  create_table "states", :force => true do |t|
    t.string "name",         :default => "", :null => false
    t.string "abbreviation", :default => "", :null => false
  end

  create_table "users", :force => true do |t|
    t.string   "login",            :limit => 64, :default => "", :null => false
    t.string   "email",                          :default => "", :null => false
    t.string   "crypted_password", :limit => 64, :default => "", :null => false
    t.string   "salt",             :limit => 64, :default => "", :null => false
    t.datetime "created_at"
    t.datetime "updated_at"
  end

end
